id: PDF971794
initial_creation_type: ocr
source_metadata:
  volumes:
    f8e7bc94797a468ea5f6b7c04657e900:
      base_file: v049.txt
      image_group_id: I1PD95894
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པའི་ཚུལ་གྱི་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1182
      volume_number: 49
